CREATE TABLE FriendshipRequests(
	Id INT NOT NULL AUTO_INCREMENT,
	RequesterId VARCHAR(255) NOT NULL,
	RequesteeId VARCHAR(255) NOT NULL,
	Outcome VARCHAR(255),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ModifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (Id),
	UNIQUE KEY `users` (RequesterId, RequesteeId),
	FOREIGN KEY (RequesterId) 
		REFERENCES Users(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (RequesteeId) 
		REFERENCES Users(Id)
		ON DELETE CASCADE
);

CREATE TABLE Friendships(
	Id INT NOT NULL AUTO_INCREMENT,
	User1Id VARCHAR(255) NOT NULL,
	User2Id VARCHAR(255) NOT NULL,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ModifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (Id),
	UNIQUE KEY `users` (User1Id, User2Id),
	FOREIGN KEY (User1Id) 
		REFERENCES Users(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (User2Id) 
		REFERENCES Users(Id)
		ON DELETE CASCADE
)